version: "3.8"
services:
 db:
  image: postgis/postgis:13-master
  environment:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
   - API_USER
   - API_PASSWORD
  ports:
   - $DB_PORT:$DB_PORT
  volumes:
   - ./db/data:/var/lib/postgresql/data
  #  - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
  restart: always
  command: -p $DB_PORT
 api:
  depends_on:
   - db
  build: ./api
  environment:
   - NODE_ENV
   - PORT=$API_PORT
   - PGHOST
   - PGPORT
   - PGDATABASE
   - PGUSER
   - PGPASSWORD
  ports:
   - $API_PORT:$API_PORT
  volumes:
   - ./api:/app
   - /app/node_modules
