version: "3"
services:
 db:
  image: postgis/postgis:13-master
  environment:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  ports:
   - $DB_PORT:$DB_PORT
  volumes:
   - ./db/data:/var/lib/postgresql/data
  restart: always
  command: -p $DB_PORT
 api:
  depends_on:
   - db
  build: ./api
  environment:
   - NODE_ENV
   - PORT=$API_PORT
   - PGHOST
   - PGPORT
   - PGDATABASE
   - PGUSER
   - PGPASSWORD
  ports:
   - $API_PORT:$API_PORT
  volumes:
   - ./api:/app
   - /app/node_modules
 ui:
  image: nginx
  environment:
   - NODE_ENV
   - REACT_APP_API_HOST
   - REACT_APP_MAPBOX_ACCESS_TOKEN
  ports:
   - 80:80
  volumes:
   - ./ui/build:/usr/share/nginx/html
